import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "hello world": 'Hello World',
          'message': 'Welcome Nikhil',
          'title': 'Flutter Language - Localization',
          'sub': 'Subscribe Now',
          'changelang': 'App Language',
          'Profile': 'Profile',
          'You are in Guest Mode,': 'You are in Guest Mode,',
          'Name': 'Name',
          'Dark theme': 'Dark theme',
          'Settings': 'Settings',
          'Logout': 'Logout',
          'Invite Friends': 'Invite Friends',
          'Rate us': 'Rate us',
          'Station': 'Station',
          'PNR': 'PNR',
          'Tickets': 'Tickets',
          'From Station': 'From Station',
          'To Station': 'To Station',
          'Date of Journey': 'Date of Journey',
          'Select Coach': 'Select Coach',
          'Select Quota': 'Select Quota',
          'General Quota': 'General Quota',
          'Tatkal Quota': 'Tatkal Quota',
          'Ladies Quota': 'Ladies Quota',
          'SL - Sleeper': 'SL - Sleeper',
          '3A - Third AC': '3A - Third AC',
          '2A - Second AC': '2A - Second AC',
          'Passenger Details': 'Passenger Details',
          'Male': 'Male',
          'Female': 'Female',
          'Transgender': 'Transgender',
          'Full Name': 'Full Name',
          'Age': 'Age',
          'No Preference': 'No Preference',
          'Lower Berth': 'Lower Berth',
          'Middle Berth': 'Middle Berth',
          'Upper Berth': 'Upper Berth',
          'Side Lower': 'Side Lower',
          'Side Upper': 'Side Upper',
          'Contact Information': 'Contact Information',
          'Your tickets will be send to the below details':
              'Your tickets will be send to the below details',
          'Enter Mobile Number': 'Enter Mobile Number',
          'Enter Email': 'Enter Email',
        },
        'hi_IN': {
          "hello world": 'हेलो विश्व',
          'message': 'निखिल का स्वागत है',
          'title': 'स्पंदन भाषा - स्थानीयकरण',
          'sub': 'अब सदस्यता लें',
          'changelang': 'ऐप की भाषा बदलें',
          'Profile': 'प्रोफ़ाइल',
          'You are in Guest Mode,': 'आप अतिथि मोड में हैं,',
          'Name': 'नाम',
          'Dark theme': 'डार्क थीम',
          'Settings': 'समायोजन',
          'Logout': 'लॉग आउट',
          'Invite Friends': 'मित्रों को आमंत्रित करें',
          'Rate us': 'हमें रेटिंग दें',
          'Station': 'स्टेशन',
          'PNR': 'पी एन आर',
          'Tickets': 'टिकट',
          'From Station': 'स्टेशन से',
          'To Station': 'स्टेशन पर',
          'Date of Journey': 'यात्रा की तारीख',
          'Select Coach': 'कोच चुनें',
          'Select Quota': 'कोटा चुनें',
          'General Quota': 'सामान्य कोटा',
          'Tatkal Quota': 'तत्काल कोटा',
          'Ladies Quota': 'महिला कोटा',
          'SL - Sleeper': 'स्लीपर',
          '3A - Third AC': 'थर्ड एसी',
          '2A - Second AC': 'सेकंड एसी',
          'Passenger Details': 'यात्री विवरण',
          'Male': 'पुरुष',
          'Female': 'महिला',
          'Transgender': 'ट्रांसजेंडर',
          'Full Name': 'पूरा नाम',
          'Age': 'आयु',
          'No Preference': 'कोई वरीयता नहीं',
          'Lower Berth': 'निचली शायिका',
          'Middle Berth': 'मिडिल बर्थ',
          'Upper Berth': 'ऊपर की शैय्या',
          'Side Lower': 'साइड लोअर',
          'Side Upper': 'साइड अपर',
          'Contact Information': 'संपर्क जानकारी',
          'Your tickets will be send to the below details':
              'आपके टिकट नीचे दिए गए विवरण पर भेजे जाएंगे',
          'Enter Mobile Number': 'मोबाइल नंबर दर्ज करें',
          'Enter Email': 'ईमेल दर्ज करें',
        },
        'ml_IN': {
          "hello world": 'ഹലോ ലോകം',
          'message': 'സ്വാഗതം നിഖിൽ',
          'title': 'ഫ്ലട്ടർ ഭാഷ - പ്രാദേശികവൽക്കരണം',
          'sub': 'ഇപ്പോൾ സബ്സ്ക്രൈബ് ചെയ്യുക',
          'changelang': 'ആപ്പ് ഭാഷ മാറ്റുക',
          'Profile': 'പ്രൊഫൈൽ',
          'You are in Guest Mode,': 'നിങ്ങൾ ഗസ്റ്റ് മോഡിലാണ്,',
          'Name': 'പേര്',
          'Dark theme': 'ഇരുണ്ട തീം',
          'Settings': 'ക്രമീകരണങ്ങൾ',
          'Logout': 'പുറത്തുകടക്കുക',
          'Invite Friends': 'സുഹൃത്തുക്കളെ ക്ഷണിക്കുക',
          'Rate us': 'ഞങ്ങളെ റേറ്റുചെയ്യുക',
          'Station': 'സ്റ്റേഷൻ',
          'PNR': 'പി.എൻ.ആർ',
          'Tickets': 'ടിക്കറ്റ്',
          'From Station': 'പുറപ്പെടുന്ന സ്റ്റേഷൻ',
          'To Station': 'പോകുന്ന സ്റ്റേഷൻ',
          'Date of Journey': 'യാത്രാ തീയതി',
          'Select Coach': 'കോച്ച് തിരഞ്ഞെടുക്കുക',
          'Select Quota': 'ക്വാട്ട തിരഞ്ഞെടുക്കുക',
          'General Quota': 'ജനറൽ ക്വാട്ട',
          'Tatkal Quota': 'തത്കാൽ ക്വാട്ട',
          'Ladies Quota': 'സ്ത്രീകളുടെ ക്വാട്ട',
          'SL - Sleeper': 'സ്ലീപ്പർ',
          '3A - Third AC': 'തേർഡ് എസി',
          '2A - Second AC': 'സെക്കൻഡ് എസി',
          'Passenger Details': 'യാത്രക്കാരുടെ വിശദാംശങ്ങൾ',
          'Male': 'ആൺ',
          'Female': 'സ്ത്രീ',
          'Transgender': 'ട്രാൻസ്‌ജെൻഡർ',
          'Full Name': 'പൂർണ്ണമായ പേര്',
          'Age': 'പ്രായം',
          'No Preference': 'മുൻഗണന ഇല്ല',
          'Lower Berth': 'ലോവർ ബർത്ത്',
          'Middle Berth': 'മിഡിൽ ബർത്ത്',
          'Upper Berth': 'അപ്പർ ബർത്ത്',
          'Side Lower': 'സൈഡ് ലോവർ',
          'Side Upper': 'സൈഡ് അപ്പർ',
          'Contact Information': 'ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ',
          'Your tickets will be send to the below details':
              'നിങ്ങളുടെ ടിക്കറ്റുകൾ ചുവടെയുള്ള വിശദാംശങ്ങളിലേക്ക് അയയ്ക്കും',
          'Enter Mobile Number': 'മൊബൈൽ നമ്പർ നൽകുക',
          'Enter Email': 'ഇമെയിൽ നൽകുക',
        }
      };
}
